const character = {
	PSshouyige: {
		sex: "male",
		group: "shen",
		hp: 8,
		skills: ["PSshuangquan"],
		dieAudios: ["die:../audio/die/shen_lvbu.mp3"],
		isBossAllowed: true,
		isBoss: true,
		trashBin: [],
	},
	PSrexusheng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["PSpojun"],
		dieAudios: ["die:../audio/die/re_xusheng.mp3"],
		trashBin: [],
	},
	PSsunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["PSzhiheng", "rejiuyuan"],
		dieAudios: [],
		trashBin: [],
	},
	PScaocao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["PSjianxiong", "rehujia"],
		isZhugong: true,
		dieAudios: [],
		trashBin: [],
	},
	PSdianwei: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["PSqiangxi", "PSsizhan"],
		dieAudios: [],
		trashBin: [],
	},
	PSzhangjiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["PSleiji", "guidao", "huangtian"],
		dieAudios: [],
		trashBin: [],
	},
	PSsunshangxiang: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["PSxiaoji", "PSjieyin"],
		dieAudios: [],
		trashBin: [],
	},
	PSliuzan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["PSfenyin"],
		dieAudios: [],
		trashBin: [],
	},
	PSyuanshu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["rewangzun", "retongji", "PSjiwei"],
		dieAudios: [],
		trashBin: [],
	},
	PSzhanghe: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["PSqiaobian"],
		dieAudios: [],
		trashBin: [],
	},
	PSsh_zhangfei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["PSshihuang", "PSpaoxiao"],
		dieAudios: ["die:../audio/die/zhangfei.mp3"],
		trashBin: [],
	},
	PStongxiangge: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["PStongxiang"],
		dieAudios: ["die:../audio/die/maliang.mp3"],
		trashBin: [],
	},
	PSrs_wolong: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["PSranshang", "bazhen", "rehuoji", "rekanpo", "cangzhuo"],
		dieAudios: ["die:../audio/die/re_sp_zhugeliang.mp3"],
		trashBin: [],
	},
	PShuanggai: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["PSkurou", "zhaxiang"],
		dieAudios: [],
		trashBin: [],
	},
	PSxushao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["PSpingjian"],
		dieAudios: [],
		trashBin: [],
	},
	PScaoxiu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["PSqianju", "PSqingxi"],
		dieAudios: [],
		trashBin: [],
	},
	PSshen_zhuge: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["PSqixing", "PSkuangfeng", "PSdawu"],
		dieAudios: ["die:../audio/die/shen_zhugeliang.mp3"],
		trashBin: [],
	},
	PShuangyueying: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["PSjizhi", "PSqicai"],
		dieAudios: [],
		trashBin: [],
	},
	PSshen_ganning: {
		sex: "male",
		group: "shen",
		hp: 3,
		maxHp: 6,
		skills: ["drlt_poxi", "PSjieying"],
		dieAudios: [],
		trashBin: [],
	},
	PSguanning: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 7,
		skills: ["PSdunshi"],
		dieAudios: [],
		trashBin: [],
	},
	PSzhaoxiang: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["refanghun", "PSfushi"],
		dieAudios: [],
		trashBin: [],
	},
	PSlukang: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["drlt_qianjie", "PSjueyan", "drlt_poshi"],
		dieAudios: [],
		trashBin: [],
	},
	PSliru: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["PSjuece", "remieji", "xinfencheng"],
		dieAudios: [],
		trashBin: [],
	},
	PScaoang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["PSkangkai"],
		isAiForbidden: true,
		dieAudios: [],
		trashBin: [],
	},
	PSzuoci: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["PShuashen", "PSxinsheng"],
		dieAudios: [],
		trashBin: [],
	},
	PSzhoutai: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["PSbuqu", "PSfenji"],
		dieAudios: [],
		trashBin: [],
	},
	PSerciyuan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["PSzanhe"],
		dieAudios: ["die:../audio/die/yuantanyuanshang.mp3"],
		trashBin: [],
	},
	PSdahantianzi: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["PSshengshi", "PSluanshi", "PSshanrang"],
		dieAudios: ["die:../audio/die/liuxie.mp3"],
		isAiForbidden: true,
		trashBin: [],
	},
	PSnanhualaoxian: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["PSyufeng", "PStianshu", "PSyinshi"],
		isAiForbidden: true,
		dieAudios: [],
		trashBin: [],
	},
	PSzhangsong: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["PSqiangzhi", "PSxiantu"],
		dieAudios: [],
		trashBin: [],
	},
	PSquansun: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["PShengzhi", "PSnengwan"],
		dieAudios: ["die:../audio/die/re_sunquan.mp3"],
		isZhugong: true,
		trashBin: [],
	},
	PSjiesuanjie: {
		sex: "female",
		group: "wu",
		hp: 4,
		skills: ["PSzailaiyici"],
		dieAudios: ["die:../audio/die/zhangxuan.mp3"],
		trashBin: [],
	},
	PSguanyunchang: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["wusheng", "PSweizhen"],
		dieAudios: ["die:../audio/die/re_guanyu.mp3"],
		trashBin: [],
	},
	PSshen_zhaoyun: {
		sex: "male",
		group: "shen",
		hp: 2,
		skills: ["PSjuejing", "relonghun"],
		isAiForbidden: true,
		dieAudios: [],
		trashBin: [],
	},
	PSzhangxuan: {
		sex: "female",
		group: "wu",
		hp: 4,
		skills: ["PStongli"],
		isAiForbidden: true,
		dieAudios: [],
		trashBin: [],
	},
	PScenhun: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["jishe", "PSlianhuo"],
		dieAudios: [],
		trashBin: [],
	},
	PSshiniangongzhu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["PSshanjia"],
		dieAudios: ["die:../audio/die/caoang.mp3"],
		trashBin: [],
	},
	PScaojinyu: {
		sex: "female",
		group: "wei",
		hp: 4,
		skills: ["PSyuqi", "PSshanshen", "PSxianjing"],
		dieAudios: ["die:ext:PS武将/audio/die/PScaojinyu.mp3"],
		trashBin: [],
	},
	PSzhaoyun: {
		sex: "male",
		group: "shu",
		hp: 5,
		skills: ["longdan", "PShuwei"],
		dieAudios: [],
		trashBin: [],
	},
	PScaochun: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["PSreshanjia", "PSxiaorui"],
		dieAudios: [],
		trashBin: [],
	},
	PScaoshuang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["PStuogu", "shanzhuan"],
		dieAudios: [],
		trashBin: [],
	},
	PSxian_caozhi: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["PSluoying", "PSjiushi"],
		dieAudios: ["die:../audio/die/re_caozhi.mp3"],
		trashBin: [],
	},
	PSsunben: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["oljiang", "PSbaiban", "PSbb_hunzi", "olzhiba"],
		dieAudios: ["die:../audio/die/re_sunben.mp3"],
		isZhugong: true,
		trashBin: [],
	},
	PSduyu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["PSmiewu", "PSqiyang"],
		dieAudios: ["die:../audio/die/sp_duyu.mp3"],
		trashBin: [],
	},
	PSshen_jiangweix: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["PSjiufa", "PSkefu", "PSwantian"],
		dieAudios: ["die:shen_jiangwei.mp3"],
		trashBin: [],
	},
	PShs_zhonghui: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["PSmn_quanji", "PSmn_paiyi"],
		dieAudios: ["die:../audio/die/xin_zhonghui.mp3"],
		trashBin: [],
	},
	PSzhuangbeidashi: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["pytianjiang", "pyzhuren", "xinfu_jingxie1", "PSshenzhu"],
		dieAudios: ["die:../audio/die/puyuan.mp3"],
		trashBin: [],
	},
	PSboss_lvbu1: {
		sex: "male",
		group: "shen",
		hp: 8,
		skills: ["wushuang", "PSjingjia1", "PSaozhan1", "PSbaguan1"],
		dieAudios: ["die:../audio/die/boss_lvbu1.mp3"],
		isBossAllowed: true,
		isBoss: true,
		trashBin: [],
	},
	PSboss_lvbu2: {
		sex: "male",
		group: "shen",
		hp: 6,
		skills: ["wushuang", "PSshenwei2", "PSshenji2", "PSbaguan2"],
		dieAudios: ["die:../audio/die/boss_lvbu1.mp3"],
		trashBin: [],
	},
	PSboss_lvbu3: {
		sex: "male",
		group: "shen",
		hp: 6,
		skills: ["wushuang", "PSshenqu3", "PSjiwu3", "PSbaguan2"],
		dieAudios: ["die:../audio/die/boss_lvbu1.mp3"],
		trashBin: [],
	},
	PSboss_lvbu4: {
		sex: "male",
		group: "shen",
		hp: 6,
		skills: ["wushuang", "PSkuangbao4", "PSshenfen4", "PSbaguan2"],
		dieAudios: ["die:../audio/die/boss_lvbu1.mp3"],
		trashBin: [],
	},
	PSshengui: {
		sex: "male",
		group: "shen",
		hp: 6,
		skills: ["wushuang", "PSshenqu", "PSjiwu"],
		dieAudios: ["die:../audio/die/boss_lvbu1.mp3"],
		trashBin: [],
	},
	PSzhangrang: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["PStaoluan"],
		isAiForbidden: true,
		dieAudios: [],
		trashBin: [],
	},
	PSxizhicai: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["tiandu", "PSxianfu", "PSchouce"],
		dieAudios: [],
		trashBin: [],
	},
	PSxiahoujie: {
		sex: "male",
		group: "wei",
		hp: 5,
		skills: ["PSdanda"],
		dieAudios: [],
		trashBin: [],
	},
	PSqun_sunce: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 5,
		skills: ["PSxiaozhan", "PSzengxi"],
		dieAudios: ["die:../audio/die/re_sunben.mp3"],
		trashBin: [],
	},
	PSgaoguimingmen: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["PSluansha"],
		dieAudios: ["die:../audio/die/xin_yuanshao.mp3"],
		trashBin: [],
	},
	PSsishouyige: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["PShengce"],
		dieAudios: [],
		trashBin: [],
	},
	db_PSdaweiwuwang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["PSdwww_zhiheng", "PSxiangong", "PScuicheng"],
		dieAudios: ["die:../audio/die/re_sunquan.mp3"],
		doubleGroup: ["wei", "wu"],
		trashBin: [],
	},
	PShw_sunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["rezhiheng", "PShuiwan", "rejiuyuan"],
		dieAudios: ["die:../audio/die/re_sunquan.mp3"],
		trashBin: [],
	},
	PSyangbiao: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["PSzhaohan", "rangjie", "PSyizheng"],
		isAiForbidden: true,
		dieAudios: [],
		trashBin: [],
	},
	PSguosi: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["PStanbei", "PSsidao"],
		dieAudios: [],
		trashBin: [],
	},
	PSshen_huangzhong: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["PSdingjun"],
		dieAudios: ["die:../audio/die/sb_huangzhong.mp3"],
		trashBin: [],
	},
	PSshen_guojia: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["PShuishi", "stianyi", "resghuishi"],
		dieAudios: [],
		trashBin: [],
	},
	PSzhenji: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["PSluoshen", "PSqingguo"],
		dieAudios: [],
		trashBin: [],
	},
	PSwu_zhangliao: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 6,
		skills: ["PSwu_tuxi", "PSwu_zhenzhan"],
		dieAudios: ["die:../audio/die/re_zhangliao.mp3"],
		trashBin: [],
	},
	PSsunru: {
		sex: "female",
		group: "wu",
		hp: 4,
		skills: ["PSyingjian", "PSshixin"],
		isAiForbidden: true,
		dieAudios: [],
		trashBin: [],
	},
	PSfuzhijie: {
		sex: "female",
		group: "wu",
		hp: 4,
		skills: ["PSfuzhi"],
		dieAudios: ["die:../audio/die/zhangxuan.mp3"],
		trashBin: [],
	},
	PSfx_shen_guanyu: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["PSshenwu", "PShunwu"],
		dieAudios: ["die:../audio/die/shen_guanyu.mp3"],
		trashBin: [],
	},
	PSpeixiu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["PSxingtu", "PSjuezhi"],
		dieAudios: [],
		trashBin: [],
	},
	PSshen_liubei: {
		sex: "male",
		group: "shen",
		hp: 6,
		skills: ["PSlongnu", "PSlb_jieying"],
		dieAudios: [],
		trashBin: [],
	},
	PSjin_duyu: {
		sex: "male",
		group: "jin",
		hp: 4,
		skills: ["PSsanchen", "PSzhaotao", "PSpozhu"],
		dieAudios: ["die:../audio/die/duyu.mp3"],
		trashBin: [],
	},
	PSsb_xushao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["PSsb_pingjian"],
		dieAudios: ["die:../audio/die/xushao.mp3"],
		trashBin: [],
	},
	PSxushi: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["PSwengua", "PSfuzhu"],
		dieAudios: [],
		trashBin: [],
	},
	PSjiaxu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["PSluanwu", "PSwansha", "reweimu"],
		dieAudios: [],
		trashBin: [],
	},
	PSshen_zhangliao: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["PSduorui", "drlt_zhiti"],
		dieAudios: [],
		trashBin: [],
	},
	PSguanyu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["PSwusheng", "PSyijue", "PSmashu"],
		dieAudios: [],
		trashBin: [],
	},
	PSshen_zhangfei: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["PSshencai", "PSxunshi"],
		dieAudios: [],
		trashBin: [],
	},
	PSmeng_liubei: {
		sex: "male",
		group: "shu",
		hp: 1,
		skills: ["PStaoyuan", "PSshiren"],
		dieAudios: ["die:../audio/die/re_liubei.mp3"],
		trashBin: [],
	},
	PSshen_dengai: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["dctuoyu", "PSxianjin", "dcqijing"],
		dieAudios: [],
		trashBin: [],
	},
	PSshen_xunyu: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["PSlingce", "PStianzuo", "PSdinghan"],
		dieAudios: [],
		trashBin: [],
	},
	PShaozhao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["PSzhengu"],
		dieAudios: [],
		trashBin: [],
	},
	PSxuyou: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["PSchenglve", "PSshicai", "nzry_cunmu"],
		dieAudios: [],
		trashBin: [],
	},
	PSshen_sunquan: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["PSyuheng", "PSdili"],
		dieAudios: [],
		trashBin: [],
	},
	PSshen_dianwei: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["PSjuanjia", "qiexie", "cuijue"],
		dieAudios: [],
		trashBin: [],
	},
	PSlvmeng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["PSbolan"],
		dieAudios: ["die:../audio/die/re_lvmeng.mp3"],
		trashBin: [],
	},
	PSzhonghui: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["clanyuzhi", "PSquanshu", "clanbaozu", "PSpaiyi"],
		dieAudios: ["die:../audio/die/clan_zhonghui.mp3"],
		trashBin: [],
	},
	PSlibai: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["PSjiuxian", "PSshixian"],
		dieAudios: [],
		trashBin: [],
	},
	PSxie_sunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["PSzongheng", "PSxiqu", "PSchengchen"],
		dieAudios: ["die:../audio/die/re_sunquan.mp3"],
		trashBin: [],
	},
	PSshu_sunshangxiang: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["PSliangzhu", "PSfanxiang"],
		dieAudios: ["die:../audio/die/sp_sunshangxiang.mp3"],
		trashBin: [],
	},
	PSmenghuo: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["PShuoshou", "PSxingluan"],
		dieAudios: ["die:../audio/die/re_menghuo.mp3"],
		trashBin: [],
	},
	PSzhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["PSjiqiao", "PShuoji", "PSpingnan"],
		dieAudios: [],
		trashBin: [],
	},
	PSpanzhangmazhong: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["PSduodao", "PSanjian"],
		dieAudios: [],
		trashBin: [],
	},
	PSlingcao: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["PSdujin", "PSgudan"],
		dieAudios: [],
		trashBin: [],
	},
	PSliubei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["PSrende", "rejijiang"],
		isZhugong: true,
		dieAudios: [],
		trashBin: [],
	},
	PScaoren: {
		sex: "male",
		group: "wei",
		hp: 2,
		maxHp: 5,
		skills: ["PSjushou", "PSbianzhen"],
		dieAudios: [],
		trashBin: [],
	},
	PSzhangfei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["PSrepaoxiao", "PSliyong"],
		dieAudios: [],
		trashBin: [],
	},
	PSreluxun: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["PSreqianxun", "PSrelianying"],
		dieAudios: [],
		trashBin: [],
	},
	PSxurong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["PSxionghuo", "PSshajue"],
		dieAudios: [],
		trashBin: [],
	},
	PSlifeng: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["PStunchu", "PSshuliang"],
		dieAudios: [],
		trashBin: [],
	},
	PSchenshi: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["PSqingbei"],
		dieAudios: [],
		trashBin: [],
	},
	PSben_sunben: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["jiang", "PShunzi", "zhiba"],
		dieAudios: ["die:../audio/die/sunce.mp3"],
		trashBin: [],
	},
	PSqun_zhaoyun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["PSlongwei", "PSqiangshu"],
		dieAudios: [],
		trashBin: [],
	},
	PSxuzhu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["PSluoyi", "PShanzhan"],
		dieAudios: [],
		trashBin: [],
	},
	PSgongsunzan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["PSdangkou", "PSbaima"],
		dieAudios: [],
		trashBin: [],
	},
	PSdongzhuo: {
		sex: "male",
		group: "qun",
		hp: 8,
		skills: ["PSlingbao", "PSjiuchi", "PSzongyu", "olbaonue"],
		isZhugong: true,
		dieAudios: [],
		trashBin: [],
	},
	PShuangzhong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["PSxujin"],
		dieAudios: [],
		trashBin: [],
	},
	PSshen_simayi: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["PSrenjie", "PSbaiyin"],
		dieAudios: [],
		trashBin: [],
	},
	PSyue_caiwenji: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["PSshuangjia", "dcbeifen"],
		dieAudios: [],
		trashBin: [],
	},
	PScaopi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["PSfangzhu", "PSxingshang", "songwei"],
		dieAudios: ["die:../audio/die/re_caopi.mp3"],
		isZhugong: true,
		trashBin: [],
	},
	PScaoying: {
		sex: "female",
		group: "wei",
		hp: 4,
		skills: ["PSlingren", "PSfujian"],
		dieAudios: [],
		trashBin: [],
	},
	PSdian_huanggai: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["kurou", "PSshiming"],
		dieAudios: ["die:../audio/die/huanggai.mp3"],
		trashBin: [],
	},
	PSliaohua: {
		sex: "male",
		group: "shu",
		hp: 5,
		maxHp: 6,
		skills: ["PSdangxian", "PSfuli"],
		dieAudios: ["die:../audio/die/xin_liaohua.mp3"],
		trashBin: [],
	},
	PSquyi: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["PSjiaozi", "PSfuqi"],
		dieAudios: [],
		trashBin: [],
	},
	PSmachao: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["PStieji", "PScema"],
		dieAudios: ["die:../audio/die/sb_machao.mp3"],
		trashBin: [],
	},
	PSqun_machao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["PSzhuiming", "PSjinge"],
		dieAudios: ["die:../audio/die/sp_machao.mp3"],
		trashBin: [],
	},
	PSluji: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["PShuaiju", "nzry_yili", "nzry_zhenglun"],
		dieAudios: [],
		trashBin: [],
	},
	PSluxun: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["PSqianxun", "PSlianying"],
		dieAudios: [],
		trashBin: [],
	},
	PSlvbu: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["PSwushuang", "PSbaifu", "PSpanshi"],
		dieAudios: [],
		trashBin: [],
	},
	PSshen_zuoci: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["PSshen_huashen", "PSshen_jihun", "PSshen_xinsheng"],
		dieAudios: ["die:ext:PS武将/audio/die/PSshen_zuoci.mp3"],
		trashBin: [],
	},
	PSreyuanshu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["PSshelian", "PSjixi"],
		dieAudios: ["die:../audio/die/re_yuanshu.mp3"],
		trashBin: [],
	},
	PSwenyang: {
		sex: "male",
		group: "wei",
		hp: 5,
		skills: ["PSlvli", "PSchoujue"],
		dieAudios: [],
		trashBin: [],
	}
};

export default character
