const characterIntro = {
	//武将介绍
	PSshouyige: "由“九个芒果”设计",
	PSrexusheng: "由“九个芒果”设计",
	PSsunquan: "由“九个芒果”设计",
	PScaocao: "由“九个芒果”设计",
	PSdianwei: "由“九个芒果”设计",
	PSzhangjiao: "由“九个芒果”设计",
	PSsunshangxiang: "由“九个鲨雕”设计",
	PSliuzan: "由“九个芒果”设计",
	PSyuanshu: "由“梦舞灬愁”设计",
	PSzhanghe: "由“神鬼高达”设计",
	PSsh_zhangfei: "由“风龙散人”设计",
	PStongxiangge: "由“九个芒果”设计",
	PSrs_wolong: "由“宫愿合”设计",
	PShuanggai: "由“闹够没有界徐盛”设计",
	PSxushao: "由“宫愿合”设计",
	PScaoxiu: "由“SC雁微凉”设计",
	PSshen_zhuge: "由“欧文哈尔”设计",
	PShuangyueying: "由“九个陈皮”设计",
	PSshen_ganning: "由“神鬼高达”设计",
	PSguanning: "由“杯糕萍琪派”设计",
	PSzhaoxiang: "由“神鬼高达”设计",
	PSlukang: "由“待我白衣为卿相”设计",
	PSliru: "由“欧文哈尔”设计",
	PScaoang: "由“10万原石”设计",
	PSzuoci: "由“九个芒果”设计",
	PSzhoutai: "由“欧文哈尔”设计",
	PSerciyuan: "由“曙光乘舟访人间”设计",
	PSdahantianzi: "由“一剑光寒19州”设计",
	PSnanhualaoxian: "由“一顿七只屑狐狸”设计",
	PSzhangsong: "由“子夜、night”设计",
	PSquansun: "由“神鬼高达”设计",
	PSjiesuanjie: "由“CuberPR”设计",
	PSguanyunchang: "由“你想去哪儿呢”设计",
	PSshen_zhaoyun: "由“神鬼高达”设计",
	PSzhangxuan: "由“看透一切的军师”设计",
	PScenhun: "由“欧文哈尔”设计",
	PSshiniangongzhu: '由"Kaesar”设计',
	PScaojinyu: "由“一顿七只屑狐狸”设计",
	PSzhaoyun: "由“不想再说也许可以”设计",
	PScaochun: "由“你想去哪儿呢”设计",
	PScaoshuang: "由“九个芒果”设计",
	PSxian_caozhi: '由"Kaesar”设计',
	PSsunben: "由“你想去哪儿呢”设计",
	PSduyu: "由“神鬼高达”设计",
	PSshen_jiangweix: "由“我最爱的雨雨”设计",
	PShs_zhonghui: "由“sc蓝晨跃”设计",
	PSzhuangbeidashi: "由“10万原石”和“遇见鲲啊”设计",
	PSboss_lvbu1: "由“神鬼高达”设计",
	PSboss_lvbu2: "由“神鬼高达”设计",
	PSboss_lvbu3: "由“神鬼高达”设计",
	PSboss_lvbu4: "由“神鬼高达”设计",
	PSshengui: "由“神鬼高达”设计",
	PSzhangrang: "由“一顿七只屑狐狸”设计",
	PSxizhicai: "由“九个芒果”设计",
	PSxiahoujie: "由“你想去哪儿呢”设计",
	PSqun_sunce: "由“咏雪雪”设计",
	PSgaoguimingmen: "由“希神文祖华”设计",
	PSsishouyige: "由“10万原石”设计",
	db_PSdaweiwuwang: "由“眼中藏着阿卡丽”设计",
	PShw_sunquan:
		"由“你想去哪儿呢”设计<br><br>你说得对，感觉不如界孙权，史诗第一，阴间质检员，在回合中找大制衡拆顺和+1马连卡距离随手打，找难的大制衡找无懈闪桃下的回合拆顺+1马打下去，对爆也是界权优。<br>思权拳，思如泉涌！👊😭👊<br>念权剑，念念不忘!!🗡😭🗡<br>界权掌，生生世世!!!✋😭✋<br>会玩、会玩、会玩！<br>璀璨中的凋零、制衡联合！😊👉👈😊<br>极冻中的炽烈、纵横捭阖！😚👦👧😚<br>虚无中的真言、容我三思！😁👍💪😁<br>冰霜中的独舞、则吴盛可期！😍👼👼😍",
	PSyangbiao: "由“一顿七只屑狐狸”设计",
	PSguosi: "由“你想去哪儿呢”设计",
	PSshen_huangzhong: "由“我最爱的雨雨”设计",
	PSshen_guojia: "由“九个芒果”设计",
	PSzhenji: "由“人生仁生”设计",
	PSwu_zhangliao: "由“小男孩_Official”设计",
	PSsunru: "由“一顿七只屑狐狸”设计",
	PSfuzhijie: "由“门刀臣零衣”设计",
	PSfx_shen_guanyu: "由“绿诗涵”设计",
	PSpeixiu: "由“九个芒果”设计",
	PSshen_liubei: "由“希神文祖华”设计",
	PSsb_xushao: "由“才七乓”设计",
	PSxushi: "由“眼中藏着阿卡丽”设计",
	PSjin_duyu: "由“一顿七只屑狐狸”设计",
	PSjiaxu: "由“九个芒果”设计",
	PSshen_zhangliao: "由“九个芒果”设计",
	PSguanyu: "由“一顿七只屑狐狸”设计",
	PSshen_zhangfei: "由“虚幼屎”设计",
	PSmeng_liubei: "由“遇见鲲啊”设计",
	PSshen_dengai: "由“mento last”设计",
	PSshen_xunyu: "由“一顿七只屑狐狸”设计",
	PShaozhao: "由“你想去哪儿呢”设计",
	PSxuyou: "由“神鬼高达”设计",
	PSshen_sunquan: "由“九个芒果”设计",
	PSshen_dianwei: "由“mento last”设计",
	PSlvmeng: "由“群弱智（兼群小丑）”设计",
	PSzhonghui: "由“九个鲨雕”设计",
	PSlibai: "由“九个芒果”设计",
	PSxie_sunquan: "由“一顿七只屑狐狸”设计",
	PSshu_sunshangxiang: "由“九个鲨雕”设计",
	PSmenghuo: "由“群弱智（兼群小丑）”设计",
	PSzhugeliang: "由“一顿七只屑狐狸”设计",
	PSpanzhangmazhong: "由“mento last”设计",
	PSlingcao: "由“九个鲨雕”设计",
	PSliubei: "由“九个芒果”设计",
	PScaoren: "由“mento last”设计",
	PSzhangfei: "由“九个芒果”设计",
	PSreluxun: "由“九个芒果”设计",
	PSxurong: "由“九个芒果”设计",
	PSlifeng: "由“九个芒果”设计",
	PSchenshi: "由“神鬼高达”设计",
	PSben_sunben: "由“九个芒果”设计",
	PSqun_zhaoyun: "由“九个陈皮”设计",
	PSxuzhu: "由“九个陈皮”设计",
	PSgongsunzan: "由“九个陈皮”设计",
	PSdongzhuo: "由“九个陈皮”设计",
	PShuangzhong: "由“九个陈皮”设计",
	PSshen_simayi: "由“九个芒果”设计",
	PSyue_caiwenji: "由“神鬼高达”设计",
	PScaopi: "由“九个芒果”设计",
	PScaoying: "由“九个鲨雕”设计",
	PSdian_huanggai: "由“九个陈皮”设计",
	PSliaohua: "由“mento last”设计",
	PSquyi: "由“九个陈皮”设计",
	PSmachao: "由“九个芒果”设计",
	PSqun_machao: "由“九个陈皮”设计",
	PSluji: "由“九个鲨雕”设计",
	PSluxun: "由“希霞”设计",
	PSshen_zuoci: "由“九个夜白”设计",
	PSreyuanshu: "由“九个陈皮”设计",
	PSwenyang: "由“一顿七只屑狐狸”设计",
	PSzhongyan: "由“mento last”设计",
	PSshen_nanhualaoxian: "由“mento last”设计",
	PShr_caocao: "由“九个夜白”设计",
	PSshenpei: "由“mento last”设计",
};

export default characterIntro
